# Generated by Django 5.2.7 on 2026-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_server_access',
            field=models.BooleanField(default=False),
        ),
    ]
